## Import Library

In [1]:
import pandas as pd, numpy as np

## Import Dataset

In [2]:
df= pd.read_csv('Absenteeism_data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


In [3]:
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

## Drop ID Column

In [4]:
df = df.drop('ID', axis=1)

## Grouping Reasons Column

In [5]:
#Make dummies and drop first column to prevent multicollinearity
reason_cols = pd.get_dummies(df['Reason for Absence'], drop_first=True)
reason_cols

1   2   3   4   5   6   7   8   9   10  ...  18  19  21  22  23  24  25  \
0     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
3     0   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   0   
4     0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
695   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
696   0   0   0   0   0   1   0   0   0   0  ...   0   0   0   0   0   0   0   
697   0   0   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   0   0   
698   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   0   
699   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

     26  27  28  
0     1   0   0  
1     0   0   0  
2     0   0   0  
3     0   0   0  
4     0   0   0  
..   ..  ..  ..  
695   0   0   0  
696   0   0   0  
697   0   0   0  
698   0   0   0  
699   0   0   1  

[700 rows x 27 columns]

In [6]:
df = df.drop('Reason for Absence', axis=1)

In [7]:
reason_cols.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28], dtype=int64)

Reasons for absence:
<br>
ICD10 Codes: https://icd.who.int/browse10/2016/en
<br>
I Certain infectious and parasitic diseases
<br>
II Neoplasms
<br>
III Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
<br>
IV Endocrine, nutritional and metabolic diseases
<br>
V Mental and behavioural disorders
<br>
VI Diseases of the nervous system
<br>
VII Diseases of the eye and adnexa
<br>
VIII Diseases of the ear and mastoid process
<br>
IX Diseases of the circulatory system
<br>
X Diseases of the respiratory system
<br>
XI Diseases of the digestive system
<br>
XII Diseases of the skin and subcutaneous tissue
<br>
XIII Diseases of the musculoskeletal system and connective tissue
<br>
XIV Diseases of the genitourinary system
<br>
XV Pregnancy, childbirth and the puerperium
<br>
XVI Certain conditions originating in the perinatal period
<br>
XVII Congenital malformations, deformations and chromosomal abnormalities
<br>
XVIII Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified
<br>
XIX Injury, poisoning and certain other consequences of external causes
<br>
XX External causes of morbidity and mortality
<br>
XXI Factors influencing health status and contact with health services.
<br><br>
And 7 categories without ICD:
<br>
22 patient follow-up
<br>
23 medical consultation
<br>
24 blood donation
<br>
25 laboratory examination
<br>
26 unjustified absence
<br>
27 physiotherapy
<br>
28 dental consultation
<br>

Reasons grouping:
<br>
Reason 1-14: Absence reasons due to various diseases or mental disorders
<br>
Reason 15-17: Absence reasons due to pregnancy & giving birth
<br>
Reason 18-21: Absence reasons due to health status check
<br>
Reason 21-28: Absence reasons due to light diseases

In [8]:
##Grouping the 28 type of reasons into 4 group based on the similarity
Reason_1 = reason_cols.loc[:,1:14].max(axis=1)
Reason_2 = reason_cols.loc[:,15:17].max(axis=1)
Reason_3 = reason_cols.loc[:,18:21].max(axis=1)
Reason_4 = reason_cols.loc[:,22:].max(axis=1)

In [9]:
df = pd.concat([Reason_1, Reason_2, Reason_3, Reason_4, df], axis=1)

In [10]:
df.columns.values

array([0, 1, 2, 3, 'Date', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'], dtype=object)

In [11]:
cols_name = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']
df = df.rename(columns={0:'Reason_1',1:'Reason_2', 2:'Reason_3', 3:'Reason_4'})

In [12]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [13]:
#Make a reason mod copy from df
df_reason_mod = df.copy()

## Extract day and month from date column

In [14]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [15]:
##Check column datatype
type(df_reason_mod['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [16]:
month_list = [df_reason_mod['Date'][i].month for i in range(len(df_reason_mod))]

In [17]:
day_list = [df_reason_mod['Date'][i].day for i in range(len(df_reason_mod))]

In [18]:
df_reason_mod.drop('Date', axis=1, inplace=True)

In [19]:
df_reason_mod['Month Value'] = month_list
df_reason_mod['Day of Week'] = day_list
df_reason_mod.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of Week'], dtype=object)

In [20]:
df_reason_mod = df_reason_mod[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Month Value','Day of Week',
                              'Transportation Expense', 'Distance to Work', 'Age',
                              'Daily Work Load Average', 'Body Mass Index', 'Education',
                              'Children', 'Pets', 'Absenteeism Time in Hours']]

In [21]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            7   
1         0         0         0         0            7           14   
2         0         0         0         1            7           15   
3         1         0         0         0            7           16   
4         0         0         0         1            7           23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

## Feature Engineering Education Column

Education category:
<br>
1: High school
<br>
2: Graduate
<br>
3: Postgraduate
<br>
4: Master & Doctorate
<br><br>
I featured engineer the category into just 2: 
<br>
0: High school education only
<br>
1: Higher education 

In [22]:
df_reason_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [23]:
df_reason_mod['Education'] = df_reason_mod['Education'].map({1:0,2:1,3:1,4:1})

In [24]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            7   
1         0         0         0         0            7           14   
2         0         0         0         1            7           15   
3         1         0         0         0            7           16   
4         0         0         0         1            7           23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [25]:
df_preprocessed = df_reason_mod.copy()

In [26]:
##Importing dataframe df_preprocessed into csv file to be used in building model
df_preprocessed.to_csv('Absenteeism_preprocessed.csv', index=False)